[DEV] 이메일 입력 창 & waiting view 구현
GDGoC-CAU/PuangFilm-FE pull request #20
Opened 2024-08-25 12:15 UTC by causyj

## Summary
- 이메일 입력창과 waiting view를 구현하였습니다.

## Description
- `tailwind.config.ts`에 글씨 크기 설정을 추가하였습니다.
> ex) `text-3xs : 12px`, `text-2xs : 14px`,`text-xs : 17px`

- 이메일 형식(ex : @ . com )에 맞게 이메일을 입력했을때만 '확인'버튼이 활성화됩니다.

- 지난번에 문제가 있었던 Modal창의 `rounded` 설정도 수정하였습니다.
![image](https://github.com/user-attachments/assets/959627ea-8554-4dcb-9644-96690be0b842)
![image](https://github.com/user-attachments/assets/da5227de-c9ed-41cb-87e0-acc63a61827c)

2024-08-26 05:40 UTC, falconlee236 requested changes
리뷰 완료했습니다
조금은 다른 이야기인데, 이메일이 완료된다면 따로 페이지를 만드는 것 보다 이메일 상태에 따라서 컴포넌트를 바꾸는 방식은 어떨까요?

지금 두 페이지가 서로 다른게 텍스트랑 아래 버튼 컴포넌트 뿐인것 같아서 질문 드립니다.

2024-08-26 05:40 UTC, falconlee236 commented on src/app/email/page.tsx
> +      console.log('what is your email:', email);
디버깅 용도는 작업 끝나면 삭제해 주시면 좋을것 같습니다

2024-08-26 05:40 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +      console.log('복사 성공');
여기 부분도 삭제하면 좋을것 같아요

2024-08-26 05:40 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +      console.error('복사 실패:', error);
이 부분은 항상 프론트 공부하면서 궁금한건데, 사용자 측에서 에러가 난다면 어떻게 처리를 하는게 가장 좋을까요??

이렇게 콘솔만 찍는것 보다 더 좋은 방법이 있을것 같은데 저는 잘 모르겠습니다.
고수의 도움이 필요해요 @1lsang

2024-08-28 02:02 UTC, causyj commented
좋은 생각인 것 같은데, 
waiting view는 주소만 있으면 사용자가 계속해서 들락날락할 수 있는 페이지인데 
접속할 때마다 매번 이메일 입력 상태를 확인해야하는 번거로움이 있지 않을까요?
접속을 그렇게 많이 안 할 것 같기도 한데 흠
다른 분들 의견도 궁금합니다!

2024-08-29 06:28 UTC, yymin1022 commented on src/app/waiting/page.tsx
> +      console.error('복사 실패:', error);
재시도 두세번 해보고, 안되면 사용자한테 기능이 정상 동작할 수 있는 방향으로 유도해서 새로고침으로 가이드한다거나 하면 괜찮지 않을까요?

2024-08-29 06:28 UTC, yymin1022 approved these changes
잘봤습니다~!

2024-09-01 15:10 UTC, 1lsang commented on src/app/waiting/page.tsx
> +      console.error('복사 실패:', error);
어떤 에러인지에 따라서 다를 것 같아요!

데이터 패칭처럼 실제 사용자가 서비스를 이용하는데 문제가 생길만한 동작이라면 (내부적으로 재시도 처리를 하면 더 좋고) 에러 페이지 혹은 모달창을 통해서 사용자에게 에러를 인지시키고 후속 행동을 유도(뒤로가기, 홈으로 이동하기, 새로고침, 데이터 패칭 재시도하기 등)하는 것이 필요합니다.

하지만 복사처럼 사용자가 서비스를 이용하는데 큰 문제가 없는 경우에는 보통 스낵바나 모달을 사용해서, 성공 or 실패를 알리는게 일반적인 것 같습니다.

2024-09-01 15:25 UTC, 1lsang approved these changes
> 좋은 생각인 것 같은데, waiting view는 주소만 있으면 사용자가 계속해서 들락날락할 수 있는 페이지인데 접속할 때마다 매번 이메일 입력 상태를 확인해야하는 번거로움이 있지 않을까요? 접속을 그렇게 많이 안 할 것 같기도 한데 흠 다른 분들 의견도 궁금합니다! @1lsang @ldh019

두 분 의견 다 괜찮습니다. 비즈니스 플로우 측면에서 생각한다면 상윤님 의견처럼, 최초에 입력을 한 후에는 다시 입력을 안한다는 점에서 개발적인 측면으로 유진님 의견처럼 생각할 수 있을 것 같아요.

다만 상윤님 의견처럼 한다면 API도 개발이 필요할 것 같아서 유진님이 하신대로 가도 괜찮을 것 같아요~

2024-09-02 03:14 UTC, merged