[DEV] 성별 컨셉 선택 페이지 구현
GDGoC-CAU/PuangFilm-FE pull request #22
Opened 2024-09-02 06:43 UTC by ldh019

## Summary
성별을 선택할 수 있는 페이지를 구현했습니다.

## Description
- 스스로 만든 첫 리액트 페이지 입니다... 많은 지적과 비난, 비판 질타,, 받겠습니다..
- 추가로 MyButton의 비활성화 디자인도 추가했습니다. 확인 부탁드립니다.
- 오른쪽 위 모서리에 있는 푸앙이 사진 파일도 추가했습니다.

Closes #10

2024-09-02 06:59 UTC, causyj commented on src/app/concept/page.tsx
> +                    ? '4px solid #133365'
#133365 색 `tailwind.config.ts`에서 지정해놔서 `primary-darkblue`로 접근할 수 있어요!

2024-09-02 07:03 UTC, causyj commented
고생하셨습니다 ~!!
첫 리액트 페이지인데 jotai까지 쓰시고,, 대단하십니다
다음에 PR때는 화면 캡쳐해서 올려주시면 더 좋을 것 같아요~

2024-09-02 07:06 UTC, causyj approved these changes
고생하셨습니다 ~!!
첫 리액트 페이지인데 `jotai`까지 쓰시고,, 대단하십니다
다음에 PR때는 화면 캡쳐해서 올려주시면 더 좋을 것 같아요~

2024-09-02 07:07 UTC, ldh019 commented
<img width="428" alt="image" src="https://github.com/user-attachments/assets/1762f6b3-524b-4f66-91c5-fac3da8b6f8d">
<img width="420" alt="image" src="https://github.com/user-attachments/assets/a8cf6c36-41a9-4cf8-9a34-12c57ae5030d">
<img width="423" alt="image" src="https://github.com/user-attachments/assets/e1777306-23b7-47db-a7a4-2f4a80ae2f7e">

급하게나마 이렇게라도 봐주십쇼

2024-09-02 07:12 UTC, causyj commented
흰 상자 크기 좀 더 커도 될 것 같은데요??
근데 푸앙이 위치가 다른 것 같은데요 ㅋㅋㅋ!!!!

2024-09-02 07:47 UTC, falconlee236 requested changes
역시 안드로이드 짬빠가 있어서 굉장히 UI를 잘 짠 것 같습니다.
몇가지 고치면 좋을 것 같은것 리뷰 남겨드려요
저도 허접이지만 같이 배워간다는 느낌으로 리뷰했습니다

2024-09-02 07:47 UTC, falconlee236 commented on src/app/concept/page.tsx
> +const selectedBoxAtom = atom<'female' | 'male' | null>(null);
이 부분은 전역 변수로 빼두는 것이 좋다고 생각하는데, 일단 머지 하면 제가 수정해서 알려드릴게요

2024-09-02 07:47 UTC, falconlee236 commented on src/app/concept/page.tsx
> +  const handleBoxClick = (box: 'female' | 'male') => {
text를 그대로 쓰는 것보다 enum과 같은 열겨형을 사용하면 좀더 가독성이 향상된다고 생각하는데,
프론트엔드 환경에서는 enum보다는 다른 방식으로 사용한다고 하네요 tree-shaking 관점때문이라고 하는데, 다음 사이트 참고해서 바꿔보시면 어떨까요?
[enum 대신에 사용하는 방법](https://velog.io/@hhhminme/%EB%84%A4-Enum-%EB%88%84%EA%B0%80-Typescript%EC%97%90%EC%84%9C-Enum%EC%9D%84-%EC%93%B0%EB%83%90)

2024-09-02 07:47 UTC, falconlee236 commented on src/components/MyButton.tsx
> +      href={enabled ? target : '#'}
이거 그냥 "#" 이면 리다이렉션이 블로킹 되는거였나요? 가물가물하네요

2024-09-02 07:47 UTC, falconlee236 commented on src/components/MyButton.tsx
>  interface MyButtonProps {
개인적으로 type은 밖으로 빼서 한곳에 모아두는 것이 좋은 것 같은데, 다른 분들의 의견도 궁금합니다
@1lsang @causyj

2024-09-02 08:01 UTC, ldh019 commented on src/app/concept/page.tsx
> +const selectedBoxAtom = atom<'female' | 'male' | null>(null);
저기 말고 더 바깥에 뺄 수 있는건가요?? 네!!

2024-09-02 08:03 UTC, ldh019 commented on src/components/MyButton.tsx
> +      href={enabled ? target : '#'}
네 그냥 # 하면 막힌다고 읽었어요. 근데 사실 저렇게 하고 싶었던 건 아니고 호버링할때부터 아예 클릭이 불가능하게 하고 싶었거든요.. 혹시 아시면 알려주십쇼

2024-09-02 08:03 UTC, yugenius0213 commented on src/components/MyButton.tsx
>  interface MyButtonProps {
그럼 interface 폴더 만들어서 한 군데 모아두도록 할까요/?

2024-09-02 09:08 UTC, falconlee236 commented on src/components/MyButton.tsx
>  interface MyButtonProps {
저도 이 방식이 좋은것 같습니다

2024-09-02 09:51 UTC, causyj commented on src/components/MyButton.tsx
> +      href={enabled ? target : '#'}
찾아보니까
‘#‘ 대신에 undefined 쓰거나,
style={{ pointerEvents: enabled ? 'auto' : 'none' }} 쓰면 링크를 비활성화 할 수 있는 것 같아요

아니면 비활성화됐다가 활성화되는 버튼을 공통 버튼으로 하나 만들어야 할 것 같은데, 그거로 대체해도 될 것 같아요

회색일때 버튼 누를 사람은 없을 것 같지만 ‘#‘ 쓰면 리렌더링 돼서 바꾸는 게 좋지 않을까하는 의견입니다!

2024-09-03 03:03 UTC, ldh019 commented on src/app/concept/page.tsx
> +  const handleBoxClick = (box: 'female' | 'male') => {
수정했습니다!

2024-09-03 03:05 UTC, ldh019 commented on src/components/MyButton.tsx
> +      href={enabled ? target : '#'}
수정했습니다!

2024-09-04 06:06 UTC, falconlee236 commented on src/components/MyButton.tsx
>  interface MyButtonProps {
@ldh019 혹시 이 부분 다 했나요? 다하면 저한테 re-request review 날려주십쇼

2024-09-05 08:11 UTC, falconlee236 approved these changes
아 훌륭합니다 리뷰 보면 바로 머지 해주세용

2024-09-05 08:22 UTC, merged