[DEV] 프로필 프레임 - 프레임 변경 & 사진 다운로드 구현
GDGoC-CAU/PuangFilm-FE pull request #25
Opened 2024-09-12 12:27 UTC by causyj

## Summary
AI로 생성된 사진에  프레임으로 꾸미는 화면을 구현하였습니다. 

## Description

- 기본/프리미엄 프레임을 골라 사진에 적용할 수 있는 기능을 구현하였습니다.
- 프레임을 선택한 후 다운로드 받을 수 있는 기능을 구현하였습니다. 
> 노트북 / 아이폰 / 아이패드로 잘 다운로드 되는 것을 확인함 
- 마지막 프리미엄 프레임은 디자인 수정되는 대로 바꿀 예정 (사이즈 이슈) 
- 현재 AI로 생성된 사진을 임의로 string값으로 사진을 넣어두어서 구현했는데, 백엔드와 코드를 합치고 난 뒤 받아오는 사진 값에 따라 다시 수정할 예정입니다.
- [Merge되면 확인해주셔하는 부분]
> 1. 프레임이 없는 경우(처음 페이지 렌더링 되었을때 / 첫번째 기본 프레임 눌렀을 때 ) 사진 다운로드 잘 되는지
> 2. 각 기본/프리미엄 프레임 눌렀을때 사진 잘 다운로드 되는지
> 3. 2번째 프리미엄 프레임 눌렀을때 사진 비율 맞게 다운로드 되는지(2번째 프리미엄 프레임만 사이즈가 다르기 때문입니다) 
프레임 선택과 다운로드 잘 되는지 확인 부탁드립니다!

![KakaoTalk_20240912_204502113](https://github.com/user-attachments/assets/d5be7e73-5b06-487d-9c64-d23cb98f179b)
![KakaoTalk_20240912_204459983](https://github.com/user-attachments/assets/65eeb3b7-d839-4c26-86c9-7695fd122844)
![KakaoTalk_20240912_204502113_01](https://github.com/user-attachments/assets/4f5ae9db-0b09-402e-8582-b74890150e59)

2024-09-13 15:32 UTC, falconlee236 requested changes
리뷰 완료했습니다!
뭔가 유진님 PR만 리뷰를 많이 다는것 같은데 양해 부탁드립니다 ㅠㅠ

2024-09-13 15:32 UTC, falconlee236 commented on .github/CODEOWNERS
CODEOWNERS라는 파일을 덕분에 처음 알게됐습니다!
나중에 써먹어볼게요.
[참고 블로그](https://helloinyong.tistory.com/329)

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/page.tsx
> +  const imageSrc = '/resultsample.png'; // 생성된 이미지(임시)
여기 부분이 AI생성된 사진이 있을때 벡엔드와 소통을 하고나서 바뀌는 부분 맞나요?

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/page.tsx
> +        {isPremiumSelected ? (
프리미엄 여부에 따라서 달라지는 부분이 className이랑 내부 택스트 뿐이라면 심항연산자를 사용하는것은 어떻게 생각하나요?

코드가 짧아질수 있을거 같아서 제안드립니다.
```suggestion
<div className=`flex h-[27px] w-[86px] items-center justify-center rounded-full ${isPremiumSelected ? "bg-white text-primary-middlegray" ? "bg-primary-darkblue text-white" }`>
</div>
```
__참고 URL__
https://stackoverflow.com/questions/74092110/how-do-i-use-ternary-operator-within-classname

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
저도 PR에서 상수를 정의했는데 아무래도
`store/constants`보다 `@/constants`가 훨씬 낫겠죠?

2024-09-13 15:32 UTC, falconlee236 commented on src/constants/index.ts
> +export const BASIC_FRAME_DATA: Record<
Record type 메모 하겠습니다. 제가 아직 모르는게 많군요
참고자료
https://cheeseb.github.io/typescript/typescript-record/

2024-09-13 15:32 UTC, falconlee236 commented on src/constants/index.ts
앞으로 수많은 상수가 있을 것 같은데 index.ts 보다는 해당 상수들을 대표할 수 있는 이름이 좋을 것 같습니다.

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/page.tsx
> +export default FrameSelectView;
이 부분은 그냥 정의부분과 합쳐도 좋을것 같습니다
```suggestion
export default function FrameSelectView () {}
```

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/_components/DownloadImage.tsx
이 함수는 컴포넌트가 아닌거 같은데, util 함수로 디렉토리를 바꾸는게 좋을것 같습니다.
또한 `tsx`확장자보다는 `ts`확장자가 맞는것 같아요

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/_components/DownloadImage.tsx
> +      context.drawImage(
다운로드 부분을 canvas로 바닐라 자바스크립트로 구현한 이유가 있을까요?
다른 다운로드 라이브러리도 있을 텐데 이 기술을 선택한 이유가 궁금합니다.

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/_components/DownloadImage.tsx
> +    alert('다운로드에 실패했습니다.');
에러가 발생할때 제가 만든 error page로 넘기면 좋을것 같습니다. 자세한 내용은 이 PR을 참고해주세요 #24

2024-09-13 15:32 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +  const [url, setUrl] = useState<string | undefined>(undefined);
이건 개인적인 코드 스타일일 수 있는데, undefined를 쓰는것 보다 그냥 빈 string을 쓰는것이 어떨까 제안합니다.
```suggestion
const [url, setUrl] = useState<string>("/");
```

undefined를 쓰면 예상치 못한 에러가 발생할 수 있는데 string을 쓰면 에러는 안날것 같기도 해서요.

2024-09-13 15:32 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +              style={{ display: 'none' }}
이거 display none이면 그냥 안보이는 컴포넌트 아닌가요? `CopyToClipboard` 라이브러리에 이 부분을 visible로 바꿔주는 기능이 있는건가요

2024-09-13 15:32 UTC, falconlee236 commented on src/app/frame/page.tsx
> +function SelectFrame({ circle, description, onClick }: FrameProps) {
이 부분은 따로 컴포넌트로 안빼고 같은 파일에 둔 이유가 궁금합니다.
작은 컴포넌트라도 밖으로 빼는게 좋지 않을까하는 생각입니다.

2024-09-14 00:11 UTC, causyj commented on .github/CODEOWNERS
괜찮습니다 ! 편하게 리뷰해주세요 ㅎㅎ
CODEOWNERS는 저도 처음 해보는거라 다음 PR때 확인을 해봐야할 것 같아요

2024-09-14 00:12 UTC, causyj commented on src/app/frame/page.tsx
> +  const imageSrc = '/resultsample.png'; // 생성된 이미지(임시)
네 아직 생성된 AI사진이 어떻게 넘어올지 몰라서 일단 임시로 사진 파일 하나 넣어두고 string 값으로 사용했습니다

2024-09-14 00:22 UTC, causyj commented on src/app/frame/page.tsx
> +        {isPremiumSelected ? (
좋은 제안 감사합니다! 수정했습니다

2024-09-14 00:39 UTC, causyj commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
주로 store는 상태 관리와 관련된 파일들을 포함한다고 하니까 store폴더랑 constants 폴더 따로 구분해서 둬도 되지 않을까요?
[참고블로그](https://thinkforthink.tistory.com/373)

2024-09-14 00:42 UTC, causyj commented on src/constants/index.ts
수정해두었습니다!

2024-09-14 00:43 UTC, causyj commented on src/app/frame/page.tsx
> +export default FrameSelectView;
수정해두었습니다

2024-09-14 00:45 UTC, causyj commented on src/app/frame/_components/DownloadImage.tsx
어 그러게요 꼼꼼한 리뷰 감사합니다

2024-09-14 00:55 UTC, falconlee236 commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
궁금한게, 저렇게 폴더링을 할때 기준은
루트인가요 app을 루트로 한 디렉토리의 기준인가요?
항상 헷갈리네요

2024-09-14 00:56 UTC, causyj commented on src/app/frame/_components/DownloadImage.tsx
> +      context.drawImage(
제가 시도해본게 html2canvas랑 html-to-image 두 라이브러리가 있었는데 이슈들이 있어서 지금의 방식으로 구현하였습니다.
 html2canvas 라이브러리는 이미지가 잘리는 현상이 있었고, 비율과 크기를 맞춰보던 중에 이를 html-to-image로 옮겼을떄 해결했다는 글을 봐서 html-to-image를 사용해봤었습니다. 그런데 html2cavas보다 다운로드 속도도 느리고 첫번째 다운로드만 이미지가 잘 생성되는 이슈가 있었습니다. 
canvas에 각 이미지들을 그리는 로직이 라이브러리보다는 저한테는 좀 더 직관적으로 와닿았고 잘 작동해서 지금 방식을 사용하였습니다.

그런데 간혹 백엔드와 연결했을때 에러가 난다는 글들이 있어서, 혹여 나중에 백엔드와 연결했을때 에러가 난다거나 코드가 너무 비효율적이라면 라이브러리도 다시 시도해보겠습니다

2024-09-14 08:27 UTC, causyj commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
루트 디렉토리로 알고 있습니다..!

2024-09-14 08:31 UTC, causyj commented on src/app/frame/_components/DownloadImage.tsx
> +    alert('다운로드에 실패했습니다.');
네 이거는 더 공부해보고 수정해두겠습니다

2024-09-14 08:34 UTC, falconlee236 commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
그럼 제가 이부분은 수정하겠습니다

2024-09-14 08:37 UTC, causyj commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
어떤 것을 수정한다는 말씀이시죠??

2024-09-14 08:40 UTC, causyj commented on src/app/waiting/page.tsx
> +  const [url, setUrl] = useState<string | undefined>(undefined);
완전 빈 string이 더 나을 것 같아서
 `const [url, setUrl] = useState<string>('');`
 이렇게 수정하였습니다

2024-09-14 09:00 UTC, causyj commented on src/app/waiting/page.tsx
> +              style={{ display: 'none' }}
아뇨 그런 기능이 있는건 아닙니다.
처음에 `CopyToClipboard`안에 링크복사 `button` 태그를 넣었을때 렌더링이 안됐어서, ref를 이용해 링크복사 `button` 을 `CopyToClipboard`태그 바깥으로 뺐습니다.

근데 지금 다시 시도해보니까 랜더링이 아예 안되는 건 아니고 엄청 늦게(한 7초쯤 후에) 렌더링이 되는 거였어요. 몇가지 실험해보니까 아마도 `CopyToClipboard`안에 내용이 복잡할수록 오래걸리는 것 같아요.

2024-09-14 09:03 UTC, causyj commented on src/app/frame/page.tsx
> +function SelectFrame({ circle, description, onClick }: FrameProps) {
그냥 작은 컴포넌트라 같이 두었었어요
수정했습니다!

2024-09-15 14:13 UTC, falconlee236 approved these changes
간단한 파일 이름만 제외하고 나머지는 다 완료된것 같아서 일단 approve 드리겠습니다
수정해주시면 될것 같아요. 고생하셨고 나머지 PR리뷰 부탁드립니다

2024-09-15 14:13 UTC, falconlee236 commented on src/constants/frameType.ts
frameType보다는 상수라는 점을 감안해서 frameData 이런식의 파일 이름은 어떨까요?

2024-09-16 05:31 UTC, causyj commented on src/app/frame/_components/DownloadImage.tsx
> +    alert('다운로드에 실패했습니다.');
그런데 생각해보니까 다운로드 실패는 페이지가 이동되면 번거로운 것 같은데, 다운로드 실패나 링크복사 같은 것들은 간단하게 alert 정도로 표시하는 게 어떨까요?

2024-09-16 05:35 UTC, causyj commented on src/constants/frameType.ts
안그래도 이 파일 이름 고민이 많았는데 `frameData`가 더 좋을 것 같아요. 수정했습니다!

2024-09-16 05:55 UTC, falconlee236 approved these changes

2024-09-17 07:02 UTC, ldh019 approved these changes
렌더링 딜레이 문제는 다 해결된거죠??

너무 어려워,,, 읽어도 뭔지 왜 잘 모르겠지,,, 그래도 최대한 이해하고... LGTM,,^^

2024-09-17 07:17 UTC, falconlee236 commented on src/app/frame/page.tsx
> +import { BASIC_FRAME_DATA, PREMIUM_FRAME_DATA } from '@/constants';
아 제가 올린 PR에는 constant 디렉토리 위치가 달라서 그 위치를 유진님 PR에 맞춰서 옮긴다는 이야기였습니다.
그리고 수정해서 PR올렸고 방금 머지 완료했습니다.
@causyj

2024-09-17 08:30 UTC, causyj commented
> 렌더링 딜레이 문제는 다 해결된거죠??
> 
> 너무 어려워,,, 읽어도 뭔지 왜 잘 모르겠지,,, 그래도 최대한 이해하고... LGTM,,^^

그 문제가 있어서 다른 걸로 바꿨지만 최선인지는 모르겠는..^^..

2024-09-17 08:31 UTC, causyj commented
> 렌더링 딜레이 문제는 다 해결된거죠??
> 
> 너무 어려워,,, 읽어도 뭔지 왜 잘 모르겠지,,, 그래도 최대한 이해하고... LGTM,,^^

그 문제가 있어서 다른 걸로 바꿨는데 그게 최선인지는 모르겠는 ..^^..

2024-09-17 08:31 UTC, merged