[DEV] 프로필 목록 화면 구현
GDGoC-CAU/PuangFilm-FE pull request #33
Opened 2024-10-01 09:17 UTC by ldh019

## Summary
프로필 목록을 확인하는 화면을 구현했습니다.

## Description
- 아직 생성한 프로필이 없는 경우, 비어있다는 화면과 함께 생성하기 버튼을 표시합니다.
- 생성한 프로필이 있는 경우 2열 스크롤 화면으로 프로필을 보여줍니다.
  - 해당 프로필을 선택하고 확인 버튼을 누르면 프레임 화면으로 이동합니다.
  
  
<img width="452" alt="image" src="https://github.com/user-attachments/assets/a51bf75e-7c8a-4629-863f-a450d8f8cf24">
<img width="429" alt="image" src="https://github.com/user-attachments/assets/343f5c48-08fe-4218-abe4-65aff7593c6c">

Closes #17

2024-10-01 09:42 UTC, yugenius0213 reviewed
고생하셨습니다~
간단한 코멘트 2개 달아서 검토 부탁드립니다!

2024-10-01 09:42 UTC, yugenius0213 commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
`IconButton`은 로그인 페이지에 있는 작은 두 버튼을 위한거라, 버튼 너비랑 안에 정렬도 안 맞는 것 같아요. `Mybutton`을 수정해서 활용하는게 좋을 것 같습니다!
`interface`에서 `name`을 `string`말고 `ReactNode`로 수정하면 이름이랑 `SVG`파일 같이 넣을 수 있지 않을까 싶습니다
혹은 다른 분들께서 더 좋은 방법이 있으면 의견 달아주세요~

2024-10-01 09:42 UTC, yugenius0213 commented on src/app/list/_components/ImageList.tsx
> +interface ListWithDataProps {
별거 아니지만 `/interfaces`에 옮겨주시면 감사하겠습니다~

2024-10-02 03:26 UTC, ldh019 commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
그럼 MyButton에도 이미지를 넣고 빼고 할 수 있는 옵션 파라미터를 추가하는게 더 나을까요? 한번 수정해볼게요!!
안그래도 저걸 쓰면서 너비가 안맞아서 좀 고민하고 있긴 했습니다요

2024-10-02 03:26 UTC, ldh019 commented on src/app/list/_components/ImageList.tsx
> +interface ListWithDataProps {
아 맞다 수정하겠습니다 ㅎㅎ

2024-10-02 04:08 UTC, ldh019 commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
<img width="423" alt="image" src="https://github.com/user-attachments/assets/d0746417-08b4-46bc-9bdc-9a975cf96fb6">
유진님 요정도면 괜찮을까요? 수정했어요!

2024-10-02 05:11 UTC, causyj commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
근데 원래 위에 첫번째 사진처럼 버튼 너비가 바깥 레이아웃에 맞게 넓어야 하는데
혹시 `Mybutton`바깥이나 부모 `div`태그에 `w-full` 한번 넣어봐주실래요??

2024-10-02 05:42 UTC, ldh019 commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
수정 완료!

2024-10-02 08:05 UTC, falconlee236 requested changes
변수 이름에 관련된 몇가지 리뷰 남겼습니다!

2024-10-02 08:05 UTC, falconlee236 commented on src/app/list/page.tsx
> +      {list.length === 0 ? <EmptyList /> : <ImageList list={list} />}
이 부분에서 list로 이상한 배열을 넘기는데, 위에서 확인해보니까 단순히 key로 넣는것 같습니다.
key를 저렇게 생성한 이유가 있을까요? 저 list를 그냥 딱 봤을 때 무슨 용도로 사용하는지 전혀 감이 잡히지 않습니다

2024-10-02 08:05 UTC, falconlee236 commented on src/app/list/_components/ImageList.tsx
> +  const handlePhotoClick = (box: string) => {
box를 선택하는 것은 좋은데 해당 string type의 box변수가 어떤 정보를 담는지 잘 모르겠습니다.
s3의 url을 담는지, 프레임의 이름을 저장하는지 불분명합니다. 지금 코드를 쭉 읽으면서 밑에 있는 list 배열의 값을 담는것 같은데 이름을 직관적으로 바꾸는것은 어떨까요?

2024-10-02 08:05 UTC, falconlee236 commented on src/components/MyButton.tsx
> +      className={`flex h-12 w-full items-center justify-center gap-5 rounded-full text-xl ${enabled ? 'bg-primary-darkblue text-white' : 'cursor-not-allowed bg-primary-gray text-primary-darkgray'}`}
이렇게 기존 컴포넌트를 수정하셨을 때 원래 있던 레이아웃이 깨지거나 그러지는 않았나요??

2024-10-02 11:56 UTC, falconlee236 commented on src/app/list/_components/EmptyList.tsx
> +      <IconButton
관련 내용은 아래에서 리뷰 했습니다 @ldh019

2024-10-03 01:27 UTC, causyj approved these changes
고생하셨습니다!

2024-10-04 03:36 UTC, ldh019 commented on src/app/list/page.tsx
> +      {list.length === 0 ? <EmptyList /> : <ImageList list={list} />}
저 리스트는 임시용입니다. 추후 API를 붙여서 프로필 목록을 받아서 넘길 예정입니다.

2024-10-04 03:38 UTC, ldh019 commented on src/app/list/_components/ImageList.tsx
> +  const handlePhotoClick = (box: string) => {
기본적으로 모든 사진들 파일명이 timestamp이기 때문에 해당 값을 저장하려고 했습니다. 이름은 혼동이 올 것 같네요 수정하겠습니다.

2024-10-04 03:38 UTC, ldh019 commented on src/components/MyButton.tsx
> +      className={`flex h-12 w-full items-center justify-center gap-5 rounded-full text-xl ${enabled ? 'bg-primary-darkblue text-white' : 'cursor-not-allowed bg-primary-gray text-primary-darkgray'}`}
푸앙이 그림 들어간 상태에선 크게 깨지는걸 본적이 없습니다요

2024-10-04 03:41 UTC, ldh019 commented on src/app/list/_components/ImageList.tsx
> +  const handlePhotoClick = (box: string) => {
이름 수정했습니다! 확인부탁드림다

2024-10-04 07:22 UTC, falconlee236 commented on src/app/list/page.tsx
> +      {list.length === 0 ? <EmptyList /> : <ImageList list={list} />}
#35 해당 이슈랑 관련된 내용 맞나요?? @ldh019

2024-10-04 07:22 UTC, falconlee236 commented on src/app/list/_components/ImageList.tsx
> +  const handlePhotoClick = (box: string) => {
그 수정하고 push 해주셔야 해용 아직 변경사항 안올라옴

2024-10-04 13:28 UTC, falconlee236 approved these changes
확인했습니다~

2024-10-07 03:03 UTC, merged