[DEV] 개인정보보호 처리 방침 BottomSheet 구현
GDGoC-CAU/PuangFilm-FE pull request #34
Opened 2024-10-02 05:24 UTC by causyj

## Summary
- 개인정보 보호 처리방침에 대한 자세한 내용을 담고 있는 BottomSheet를 구현하였습니다.
- 머지되면 `npm i` 부탁드립니다

## Description
- `bottom sheet`를 위해 `react-spring-bottom-sheet` 라이브러리를 사용하였습니다. 
>`react-spring-bottom-sheet`는 자체 css를 사용하기 때문에 ``` import 'react-spring-bottom-sheet/dist/style.css'``` 구문이 필요합니다.

- 개인정보 처리방침에 대한 내용(내용은 노션에 있습니다)을 다음과 같이 처리하였습니다.
> 숫자/유니코드 원 숫자/ * / - 를 기준으로 줄바꿈 후 각 특수기호마다 들여쓰기를 다르게 하였습니다.
> 원래 문자열로 저장해서 `whitespace-pre-wrap`으로 줄바꿈을 하려고 했는데, 표를 위해 <table>컴포넌트가 필요해서 지금의 방법을 택하게 되었습니다.
> 더 좋은 방법이 있을 것 같아서 이 부분은 다른 분들의 의견이 궁금합니다!

![image](https://github.com/user-attachments/assets/bae1b238-56c2-4367-a943-50cf369a9ea0)

2024-10-02 06:22 UTC, ldh019 approved these changes
내 눈엔 다 좋아보여 아직 리액트는 멀었다 고생했습니다용

2024-10-02 11:49 UTC, falconlee236 requested changes
상수와 관련해서 몇 가지 리뷰 남겼습니다!

2024-10-02 11:49 UTC, falconlee236 commented on .vscode/settings.json
> +{}
불필요한 파일이 있네요. 제거 요청드립니다.
추가로 gitignore에 .vscode 디렉토리 추가해주실 수 있을까요?

2024-10-02 11:49 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +function formatText(text: string) {
상수 파일에 다른 함수가 들어오는 것보다 `PrivacyPolicy.tsx` 파일에 넣는 것이 상수 파일의 통일성을 더 잘 지킬 것 같습니다.

2024-10-02 11:49 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
이 부분은 결국 컴포넌트가 아닌가요?
마찬가지로 상수 파일에 tsx 확장자가 들어있으면 더 이상 상수라고 볼 수 없을 것 같습니다.
그렇기 때문에 저는 `Table1`과 `Table2`를 `guide` 페이지 하위의 컴포넌트로 넣는 것이 좋아보이는데 이에 대해서는 어떻게 생각하시나요?

2024-10-02 11:49 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +        {[
그리고 이렇게 배열은 나중에 새로운 값이 추가되는 것을 대비해서 이 상수 파일에 두는 것이 좋아보입니다.

2024-10-02 11:49 UTC, falconlee236 commented on src/components/PrivacyPolicy.tsx
> +  return LineBreaks;
이 부분은 하나로 통합하는 것이 좋을 것 같아요
```suggestion
return text.replace()...
```

2024-10-03 01:04 UTC, causyj commented on .vscode/settings.json
> +{}
수정했습니다!

2024-10-03 01:07 UTC, causyj commented on src/constants/privatePolicyContent.tsx
> +function formatText(text: string) {
`formatText`은 아래 `privacySections`에서 필요해서 여기에 두었습니다.

2024-10-03 01:22 UTC, causyj commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
저도 이부분이 고민이 많았는데요, 
표를 만드는 `table`태그 때문에 어쩔 수 없이 상수 파일에 컴포넌트가 들어가게 되어서 저도 옮기려고 했는데, 내용이 상수부분이라 고민 끝에 상수 폴더에 넣게 되었습니다.

말씀하신대로 이 내용들을 `guide` 하위 컴포넌트에 넣기에는 공통 컴포넌트 파일에 있는 모달창에도 쓰여서요
그러면 `components`폴더에 개인정보처리방침을 위한 하위 폴더를 만드는 것은 어떠할까요?

이 폴더에 관한 부분은 PR description부분에 좀 더 덧붙여서 써두었습니다. 참고부탁드립니다~

2024-10-03 01:24 UTC, yugenius0213 commented on src/constants/privatePolicyContent.tsx
> +        {[
이 부분도 위 comment들이랑 연결되는 부분인데,
그러면 `Components`폴더에 하위폴더를 만들어 옮기고, 안의 내용들만 `.ts`파일에 둘까요?

2024-10-03 01:26 UTC, causyj commented on src/components/PrivacyPolicy.tsx
> +  return LineBreaks;
수정했습니다.

2024-10-03 01:42 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
저는 따로 하위디렉토리를 만드는것보다 컴포넌트 폴더에 넣는게 좋아보입니다
컴포넌트 폴더는 모든 곳에서 공통으로 사용되는 부분인걸로 알고있습니다. 거기에 하위디렉토리를 만들면 구조 파악이 조금 힘들것 같다는 의견입니다

2024-10-03 01:43 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +        {[
이 부분은 하위폴더 옮기는것과 별개로 일단 배열은 .ts로 옮기면 좋을것 같다는 의견이였습니다

2024-10-03 01:44 UTC, causyj commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
앗 제말은 컴포넌트 폴더 안에 하위 폴더를 만든다는 얘기였습니다!
관련 폴더가 두개여서요

2024-10-03 06:21 UTC, falconlee236 commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
하나의 컴포넌트가 필요한 파일이 여러개 있으면 `Modal` 처럼 하위로 디렉토리를 나누는 @causyj 님 의견도 괜찮아 보입니다

2024-10-03 13:05 UTC, causyj commented on src/constants/privatePolicyContent.tsx
> +export function Table1() {
수정했습니다 검토 부탁드립니다~

2024-10-03 13:05 UTC, causyj commented on src/constants/privatePolicyContent.tsx
> +        {[
수정했습니다!

2024-10-04 07:19 UTC, falconlee236 requested changes
제 기준 구조가 훨씬 깔끔해 진것 같습니다!! 
고생 많으셨습니다 그런데 그 vscode파일이 이미 github에 올라가면 local에서 .gitignore만 넣어다고 github에 있는게 아니라서 그 부분이 남아있습니다. 그것만 지워주시면 될것 같습니다

2024-10-04 07:19 UTC, falconlee236 commented on .vscode/settings.json
아직 사라진게 아니라 내용만 빈 것 같아요 레포에 올라간걸 지워주시면 감사하겠습니다!

2024-10-05 02:45 UTC, causyj commented on .vscode/settings.json
삭제했습니다! 확인 부탁드려요~

2024-10-05 04:30 UTC, falconlee236 approved these changes
모두 확인했습니다!

2024-10-06 12:53 UTC, merged