[DEV] 생성된 프로필 목록 조회
GDGoC-CAU/PuangFilm-FE pull request #37
Opened 2024-10-10 14:34 UTC by ldh019

## Summary
이전에 만들었던 프로필 목록을 확인하는 화면입니다.

## Description
- photo-request/list API call을 통해 목록을 불러옵니다.
- 화면에 사진을 클릭하고 확인 버튼을 누르면 프레임 화면으로 이동합니다.
- 이전에 만들었던 화면에 API만 추가한 PR입니다. 화면은 이전 PR을 참고해주세요. #17 

Closes #36

2024-10-10 15:04 UTC, falconlee236 requested changes
에러처리 부분만 수정 부탁드립니다!

2024-10-10 15:04 UTC, falconlee236 commented on src/app/list/page.tsx
> +            console.error(data.msg);
#21 #24 참고해서 에러 났을 때 에러 페이지로 이동할 수 있게 에러 처리 부탁드립니다
```suggest
setInsertToken('');
setErrorMessage(LOGIN_ERROR_MSG);           setErrorCheckMessage(LOGIN_ERROR_CHECK_MSG);
router.push(ROUTE_TYPES.ERROR);
```

token을 삭제하는 코드는 지워도 될것 같네요 로그인이 실패한게 아니니까

2024-10-11 00:35 UTC, causyj approved these changes
LGTM
고생 많으셨습니다~~

2024-10-11 07:10 UTC, falconlee236 approved these changes
지금 에러가 로그인 문제인지는 모르겠는데 일단 approve 할게요

2024-10-12 08:58 UTC, merged