[DEV] frame 페이지 이미지 불러오기
GDGoC-CAU/PuangFilm-FE pull request #39
Opened 2024-10-13 11:32 UTC by causyj

## Summary
- list 뷰에서 선택한 이미지가 frame 페이지에 뜨도록 하였습니다.
- ai가 생성한 이미지가 frame 페이지에 뜨도록 하였습니다.
- waiting 페이지에서 이미지 생성 api를 통해 생성 완료가 되면 frame로 라우팅하게 하였습니다. 
- 
## Description
- frame 페이지 안의 이미지가 렌더링되는 case가 2가지가 있어서 이미지 list에서 이미지가 선택되었는지 안되었는지에 따라 이미지를 다르게 띄우게 하였습니다.
> 이미지가 선택되었다면 그 이미지가 frame페이지에, 아무것도 선택되지 않았다면 ai가 생성한 이미지를 보여주게 하였습니다.
> 그러기 위해 `PreviousPage` 버튼을 누를때 list 선택을 해제하게 하였습니다. 

- 위의 로직을 위해 frame페이지에서 새로고침을 했을때 `useAtom`을 이용해 list에서 선택된 이미지가 계속 유지되어야 하는데, `useAtom`은 새로고침시 초기화가 되는 이슈가 있었습니다. 그래서 `useAtom` 대신에 상태를 `localStorage`에 저장해주는 `atomWithStorage`를 사용하여 새로고침시에도 상태가 변하지 않도록 하였습니다. 

- ai가 생성한 이미지를 불러오기 위해 이미지 목록 페이지에서 목록의 0번째 인덱스(가장 최근에 만들어진 이미지)를 사용해야해서 여기서도 `atomWithStorage`를 사용하였습니다.
> 따라서 list페이지에서 목록 중 선택한 이미지와 list[0]을 저장하는 부분에서 `atomWithStorage`를 쓰게 되었습니다. @ldh019 님의 코드를 수정한 부분이라 확인부탁드립니다!

- 또한 ``` const storedToken = window.sessionStorage.getItem('accessToken') || '';
```이 부분이 `useEffect` 바깥에 있을때 500에러가 발생해서 `useEffect`안에 있게 수정하였습니다.
> 찾아보니 Next.js가 SSR 방식으로 동작하기 때문에 window 객체를 사용하려면 클라이언트 측에서만 접근해야하기 때문에 `useEffect`안에 존재해야한다고 하는데, 똑같은 코드로 `login`에는 에러 없이 잘 작동해서 의문입니다(?)

> 이전에 더미값으로 두었던 예제 list로 코드를 테스트 해보았고, api 연결했을때도 에러 없이 잘 작동하는 것을 확인하였습니다.

`waiting` 페이지에서 `404에러`가 뜨기는 하지만, api 명세서에 적혀있는대로 유저의 최근 요청을 찾지 못했을 때인 것 같아서 일단 PR올렸습니다. 이 부분은 나중에 확인을 다시 해보겠습니다

2024-10-13 17:10 UTC, 1lsang approved these changes

2024-10-13 17:10 UTC, 1lsang commented on src/app/api/waiting/route.ts
> +    },
별건 아니지만 은닉해야할 데이터가 있는게 아니라면 API 응답값을 그대로 넣어줘도 괜찮을 것 같아요
```suggestion
    jsonData,
```

2024-10-14 01:15 UTC, causyj commented on src/app/api/waiting/route.ts
> +    },
넵 수정했습니다! 감사합니다~

2024-10-14 02:26 UTC, ldh019 commented on src/app/list/page.tsx
> +
수정 안했다더니 해주셨군요 체고체고

2024-10-14 02:26 UTC, ldh019 commented on src/store/atoms/atomWithStorage.ts
> +
감사합니당 ㅎㅎ

2024-10-14 02:27 UTC, ldh019 commented on src/app/list/_components/ImageList.tsx
> +  );
감사할 일이 많네... 유진아 고맙다,,,

2024-10-14 02:29 UTC, ldh019 approved these changes
고생했어요~!~~ LGTM~~

2024-10-14 04:13 UTC, falconlee236 requested changes
> 찾아보니 Next.js가 SSR 방식으로 동작하기 때문에 window 객체를 사용하려면 클라이언트 측에서만 접근해야하기 때문에 useEffect안에 존재해야한다고 하는데, 똑같은 코드로 login에는 에러 없이 잘 작동해서 의문입니다(?)

이 부분에 대해서 답변 드리겠습니다.

# 문제점
window객체는 브라우저에서 동작하는 친구이기 때문에 서버사이드 렌더링에서는 항상 `undefined`을 반환합니다.   
이걸 막기 위해서 `use clients`를 사용한다고 해도 또 다른 문제가 남아있습니다. 
* use client는 서버 사이드 렌더링 컴포넌트가 아니라는 선언만 할 뿐이지 next의 기본 렌더링 방식인 일괄적으로 모든 페이지를 렌더링하는 방식은 막지 않습니다.
* 서버에서 해당 파일을 일괄적으로 렌더링하기 때문에 사용자가 해당 페이지를 렌더링하는 시점에는 이미 window가 `undefined`라는 문제가 발생합니다.
* 이 문제를 막기 위해서 웹 프레임워크는 `lazy loading`을 지원합니다. 기존 방식처럼 한번에 모든 페이지를 불러오는 것이 아닌 필요할 때 마다 페이지를 불러오는 방식입니다. 
* lazy loading을 사용한다면 사용자가 이 페이지를 필요로 할때 비로소 해당 페이지가 로딩되기 때문에 window 객체를 정상적으로 받아올 수 있습니다.
# 해결방안
똑같은 코드라고 말씀하셨지만 유진님 코드랑 제 코드랑 결정적인 차이점이 맨 마지막 줄에 있습니다.

```javascript
export default dynamic(() => Promise.resolve(LoginView), {
  ssr: false,
});
```
VS
```javascript
return (
    <div className="flex w-full flex-col justify-start bg-background">
      <PreviousPage target="/login" />
      <p className="mb-3 text-center font-cafe24 text-xl text-primary-darkblue">
        나의 프로필 목록
      </p>
      {list.length === 0 && <EmptyList />}
      {!loading && list.length !== 0 && <ImageList list={list} />}
    </div>
  );
```

next에서 lazyloading을 지원하는 방식은 여러가지가 있지만 저는 다음과 같이 ssr:false option을 가진 프라미스 객체를 반환하는 형식으로 lazyloading을 구현했습니다.
* 그렇기 때문에 window객체를 useEffect 함수 안에 넣지 않더라도 사용할 수 있게 됩니다.
* 리액트나 next를 개발할때 저는 왠만하면 useEffect를 사용하지 않으려고 노력합니다. 이 함수 때문에 버그가 너무 많이 발생하고 디버깅도 힘들어지기 때문입니다. 
* 그래서 저는 useEffect에 값을 넣지않고 어떻게 `window`객체 문제를 해결할지 고민하고 나온 결과가 `lazy loading` 입니다.

# 마무리
제가 `window` 객체의 값이 로딩되는 문제를 해결한 방법을 소개해드렸습니다.  
물론 유진님이 문제를 해결한 방식이 더 마음에 드시면 그대로 머지하셔도 괜찮습니다. 저는 또 다른 해결 방안과 공부하면 좋을 토픽을 던져드린것 뿐입니다.

해당 문제 말고 다른 리뷰 밑에 남겨드렸으니까 확인해 주시면 좋을것 같습니다.

위 문제를 해결하기 위해서 필요한 참고 자료 링크 올려드리겠습니다.
[next.js lazy loading](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading)

2024-10-14 04:13 UTC, falconlee236 commented on src/app/frame/page.tsx
> +    return null;
해당 if문이 존재한다는 뜻은 isClient가 false상태로 될 수 있다는 뜻인가요?
코드를 보니까 useEffect를 사용해서 컴포넌트가 마운트 될때 상태를 관리하기 위해서 보이는데 불필요한 상태라고 생각합니다.

그리고 만약 해당 상태를 사용한다고 해도 `return null`을 해버리면 해당 컴포넌트가 렌더링이 안되게 한다는 뜻인데 그것 보다는 그냥 클라이언트 에러라는 메시지를 가지고 에러 페이지로 보내버리는 방법은 어떨지 제안 드립니다.

2024-10-14 04:13 UTC, falconlee236 commented on src/constants/errorMessages.ts
> +export const STATUS_MSG: string = '아직 사진이 생성되지 않았습니다.';
사진 생성이 실패했다는 의미를 더욱 강조하기 위해서
`STATUS_MSG` 보다 
```suggestion
export const GENERATE_IMG_ERROR_MSG: string = '아직 사진이 생성되지 않았습니다.';
```
이런식으로 바꾸는 것은 어떨까요?
밑에 있는 것도 같이 바꿔 주시는 것을 제안드립니다

2024-10-14 04:13 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +      router.push('/frame');
```suggestion
router.push(ROUTE_TYPES.FRAME);
```
`src/app/frame/page.tsx`의 43번째 줄 처럼 
해당 페이지도 routing할때 주소를 잘못 입력하는 실수를 방지하기 위해 상수를 사용하시는 것을 권장드립니다

2024-10-14 04:13 UTC, falconlee236 commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
맨 위에서 관련 내용 설명해드렸습니다.  
코드를 수정하시는 것은 PR올린 사람의 자유입니다. 편하신대로 하셔도 좋습니다!

2024-10-14 04:13 UTC, falconlee236 commented on src/app/waiting/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
맨 위에서 관련 내용 설명해드렸습니다.  
코드를 수정하시는 것은 PR올린 사람의 자유입니다. 편하신대로 하셔도 좋습니다!

2024-10-14 04:13 UTC, falconlee236 commented on src/store/atoms/atomWithStorage.ts
> +export const selectedPhotoAtomWithStorage = atomWithStorage<string>(
저도 토큰을 sessionStorage에 저장할때 이 함수를 사용하려고 했는데, 버그가 너무 많이 발생했다는 인터넷 글을 봐서 사용하지 않았습니다. 
수정사항을 제안해 볼테니 괜찮으면 반영해 주시고 복잡하면 반영 안해주셔도 좋습니다.

```suggestion
// @/store/atoms/tokenActions.ts
export const actionInsertToken = atom(
  (get) => get(tokenAtom),
  (_, set, token: string) => {
    set(tokenAtom, token);
    window.sessionStorage.setItem('accessToken', token);
  },
);
```

2024-10-14 11:06 UTC, causyj commented on src/app/frame/page.tsx
> +    return null;
오우 리뷰하는데 시간 많이 드셨겠어요 정성스런 리뷰 감사합니다~~

위 코멘트를 답변드리자면, 처음 isClient 초기값을 false로 두었습니다.
저 코드는 이미지 렌더링 지연으로 ai로 최근 생성된 이미지가 잠깐 보였다가 목록에서 선택된 이미지가 렌더링 되어서 사용했습니다.
이를 해결하기 위해 클라이언트가 완전히 준비되었을때 렌더링을 진행하도록 isClient를 사용한 것이었습니다.
그런데 이것도 위에 말씀해주신 dynamic 해결이 가능해서 에러메시지 대신 dynamic방법을 써도 괜찮을까요?

2024-10-14 11:24 UTC, causyj commented on src/constants/errorMessages.ts
> +export const STATUS_MSG: string = '아직 사진이 생성되지 않았습니다.';
밑에 `GENERATED_ERROR_MSG`가 있어서 `IMG_NOT_READY`로 바꾸고 밑에 있는거는 그 아래 `GENERATION_ERROR_MSG`랑 똑같아서 재활용했습니다

2024-10-14 11:51 UTC, yugenius0213 commented on src/app/waiting/page.tsx
> +      router.push('/frame');
이런,, 정말 꼼꼼하시군요
감사합니다~~

2024-10-14 11:57 UTC, causyj commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
넵 ㅎㅎ
그런데 한가지 궁금한 점이 있습니다! 
위에 들어주신 예시와 같이 컴포넌트를 모두 `ssr:false`로 설정하면, `ssr`이 필요한 경우에는 어떻게 하는지 궁금합니다! `ssr`을 사용해야할 때가 있을 텐데 이럴 때 어떻게`ssr`과 클라이언트 전용 컴포넌트를 병행할 수 있을까요??

2024-10-14 12:01 UTC, causyj commented on src/store/atoms/atomWithStorage.ts
> +export const selectedPhotoAtomWithStorage = atomWithStorage<string>(
자료가 별로 없긴 하더라고요
근데 `localStorage`말고 `sessionStorage` 쓰신 이유가 궁금합니다!

2024-10-15 02:17 UTC, falconlee236 commented on src/app/frame/page.tsx
> +    return null;
최대한 `useEffect`를 쓰지 않는 방향이라면 사용해도 좋을 것 같습니다

2024-10-15 02:22 UTC, falconlee236 commented on src/store/atoms/atomWithStorage.ts
> +export const selectedPhotoAtomWithStorage = atomWithStorage<string>(
저는 로그인 기록이 사용자 컴퓨터에 저장되어 있는 상태를 별로 좋게 생각하지 않아서 세션이 끝나면 세로 로그인하게 만들었습니다.  
사용자 입장에서는 로그인하는 과정이 귀찮을 수 있지만 보안이라는 관점으로 넘어가면 이는 사용자 경험과 타협할 수 없다고 생각합니다. 사용자 경험보다는 사용자 정보가 더 중요하니까요

2024-10-15 02:31 UTC, falconlee236 commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
클라이언트 컴포넌트에서 서버 컴포넌트를 사용하기 위해서는 직접 import 할 수 없습니다. 미리 클라이언트 컴포넌트 입장에서 서버 컴포넌트가 렌더링 되어있는지 모르기 때문입니다.  
하지만 클라이언트 컴포넌트에서 `children` props를 사용해서 서버 컴포넌트를 넘긴다면 클라이언트 컴포넌트에서 서버 컴포넌트를 사용할 수 있습니다.  

따라서 클라이언트 컴포넌트와 서버 컴포넌트를 함께 사용하고 싶다면 클라이언트 컴포넌트에 `children` props 를 고려해 보는 것도 좋을것 같습니다.  

그리고 이 질문에 대해서는
> 위에 들어주신 예시와 같이 컴포넌트를 모두 ssr:false로 설정하면, ssr이 필요한 경우에는 어떻게 하는지 궁금합니다! 
기본적으로 next의 app router는 SSR로 동작하고 그렇지 않은 경우에만 `use client` 를 파일 맨 위에 명시해서 사용하기 때문에 ssr이 필요하면 평소 그대로 작성하시면됩니다. lazy loading 관점에서 물어보셨다면 `ssr:false` 말고 다른 방식인 `suspense`를 참고하시면 좋을것 같네요

2024-10-15 02:38 UTC, falconlee236 reviewed
일단 지금까지 push한 내용 리뷰했습니다. 에러메시지관련 몇가지 코멘트 남겨드렸습니다.  

window 객체 문제는 해결되었는지 궁금하네요 항상 고생이 많으십니다

2024-10-15 02:38 UTC, falconlee236 commented on src/app/list/page.tsx
> -            setErrorCheckMessage(LOGIN_ERROR_CHECK_MSG);
리뷰하면서 발견한건데 setErrorCheckMessage는 왜 생략했는지 알수 있을까요? 이러면 에러 페이지가 제대로 작동하지 않을것 같아 질문드립니다.

2024-10-15 02:38 UTC, falconlee236 commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
useEffect에 의존성 배열에 없다면 굳이 useEffect안에 atom내용을 넣을 필요가 없을것 같습니다. lazy loading으로 window객체 문제를 해결했다면 더더욱 밖으로 빼놓는 것도 좋을것 같네요

2024-10-15 03:14 UTC, causyj commented on src/app/frame/page.tsx
> +    return null;
네 dynamic으로 해결하였습니다

2024-10-15 03:15 UTC, causyj commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
궁금한 부분이 해결되었습니다 감사합니다~

2024-10-15 03:16 UTC, causyj commented on src/store/atoms/atomWithStorage.ts
> +export const selectedPhotoAtomWithStorage = atomWithStorage<string>(
넵 답변 감사합니다!

2024-10-15 03:42 UTC, causyj commented on src/app/list/page.tsx
> -            setErrorCheckMessage(LOGIN_ERROR_CHECK_MSG);
로그인이나 사진 업로드 페이지와 달리 `waiting`과 `list`페이지에는 굳이 `setErrorCheckMessage`가 필요없을 것 같아서 안 넣었습니다.  안 넣어도 문제는 없을 것 같은데 혹시 몰라서 수정해두었습니다

2024-10-15 03:55 UTC, causyj commented on src/app/list/page.tsx
> +    const storedToken = window.sessionStorage.getItem('accessToken') || '';
`list` 페이지는 문제를 해결한 적이 없지만(?) 코드 수정했습니다!

2024-10-15 11:41 UTC, falconlee236 approved these changes
변경사항 모두 확인했습니다!
뭔가 리뷰를 너무 많이 남겨드린 것 같은데, 혹시라도 너무 많다고 느끼시면 말씀해주세요
항상 고생 많으십니다 승인 했습니다

2024-10-15 11:44 UTC, yugenius0213 commented
> Member

왕 감사합니다~~
많기는 한데 많이 배우기도 하고 그만큼 시간 써주시는건데 감사하죠 ^.^
덕분에 코드 쓰면서도 한번 더 생각하게 되는 습관이 생겼어요 ㅎㅎ
고생하셨습니다 ~ 끝이 보이네요~!~!

2024-10-15 11:59 UTC, merged